.build:
  stage: build
  variables:
    image_tag: $CI_REGISTRY_IMAGE/$iip_version
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - cd $iip_version
    - docker build -t $image_tag .
    - docker push $image_tag

iipimage_1.0:
  extends: .build
  iip_version: '1.0'
