stages:
  - build
  - test
  - release

variables:
  build_tag: $CI_REGISTRY_IMAGE/$iip_version:$CI_COMMIT_SHORT_SHA
  release_tag: $CI_REGISTRY_IMAGE/$iip_version:latest

.build:
  stage: build
  before_script:
    - docker version
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build --pull -t $build_tag - < $iip_version/Dockerfile
    - docker push $build_tag

.test:
  stage: test
  before_script:
    - docker version
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $build_tag
  script:
    - ./test.sh

.release:
  stage: release
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $build_tag
    - docker tag $build_tag $release_tag
    - docker push $release_tag
  only:
    - master

.iipimage_1.0:
  variables:
    iip_version: '1.0'

.iipimage_1.1:
  variables:
    iip_version: '1.1'

.iipimage_post_1.1:
  variables:
    iip_version: 'post-1.1'

build_1.0:
  extends:
    - .build
    - .iipimage_1.0

test_1.0:
  extends:
    - .test
    - .iipimage_1.0

release_1.0:
  extends:
    - .release
    - .iipimage_1.0

build_1.1:
  extends:
    - .build
    - .iipimage_1.1

test_1.1:
  extends:
    - .test
    - .iipimage_1.1

release_1.1:
  extends:
    - .release
    - .iipimage_1.1

build_post_1.1:
  extends:
    - .build
    - .iipimage_post_1.1

test_post_1.1:
  extends:
    - .test
    - .iipimage_post_1.1

release_post_1.1:
  extends:
    - .release
    - .iipimage_post_1.1
