FROM debian:buster

ARG SERVER_PORT=8080
ENV SERVER_PORT $SERVER_PORT

RUN apt-get -y update \
	&& apt-get -y install \
	iipimage-server \
	lighttpd \
	&& apt-get -y clean

COPY ./lighttpd.conf /etc/iipimage-lighttpd.conf

RUN mkdir -p -m 0444 /data
VOLUME /data

CMD ["/usr/sbin/lighttpd", "-D", "-f", "/etc/iipimage-lighttpd.conf"]

USER www-data
