version: '3.7'

services:
  iipimage:
    image: iipimage-server
    build:
      context: .
    environment:
      - VERBOSITY=5
    volumes:
      - ./images:/data

  web:
    image: iipimage-web
    ports:
      - "8080:8080"
